export const SET_WEB3 = 'SET_WEB3';
export const SET_ACCOUNTS = 'SET_ACCOUNTS';
export const SET_ISLOGGEDINTO3BOX = 'SET_ISLOGGEDINTO3BOX';
export const SET_3BOX_PROFILE = 'SET_3BOX_PROFILE';
export const SET_CONTRACTS = 'SET_CONTRACTS';
export const SET_REGISTERED_USER = 'SET_REGISTERED_USER';